import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google';
import Link from 'next/link';
import './globals.css'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next mobile dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
        <div>Header</div>
      {children}
      <div>
      <Link href={"/"}>Home</Link>
       <Link href={"/cards"}>Cards</Link>
        <Link href={"/tickets"}>Ticket</Link>
         <Link href={"/settings"}>Settings</Link>
      </div></body>

    </html>
  )
}
